import {defineField, defineType} from 'sanity'
import {MdDeveloperBoard as icon} from 'react-icons/md'

export default defineType({
  name: 'accessory',
  title: 'Accessory',
  type: 'document',
  groups: [
    {
      name: 'main',
      title: 'Main',
    },
    {
      name: 'display',
      title: 'DISPLAY',
    },
    {
      name: 'generalSpecifications',
      title: 'GENERAL SPECIFICATIONS',
    },
    {
      name: 'interactivity',
      title: 'INTERACTIVITY',
    },
    {
      name: 'computing',
      title: 'COMPUTING',
    },
    {
      name: 'audio',
      title: 'AUDIO',
    },
    {
      name: 'connectivity',
      title: 'CONNECTIVITY',
    },
    {
      name: 'panelManagement',
      title: 'PANEL MANAGEMENT',
    },
    {
      name: 'power',
      title: 'POWER',
    },
    {
      name: 'environmental',
      title: 'ENVIRONMENTAL',
    },
    {
      name: 'complianceCertification',
      title: 'COMPLIANCE & CERTIFICATION',
    },
    {
      name: 'physicalSpecifications',
      title: 'PHYSICAL SPECIFICATIONS',
    },
    {
      name: 'packedContents',
      title: 'PACKED CONTENTS',
    },
    {
      name: 'installation',
      title: 'INSTALLATION',
    },
    {
      name: 'warranty',
      title: 'WARRANTY',
    },
    {
      name: 'support',
      title: 'SUPPORT',
    },
    {
      name: 'educationSoftwareLicense',
      title: 'EDUCATION SOFTWARE LICENSE',
    },
    {
      name: 'technicalDrawings',
      title: 'TECHNICAL DRAWINGS',
    },
    {
      name: 'activInspireComparisonPreperation',
      title: 'ActivInspire Comparison Preperation',
    },
    {
      name: 'activInspireComparisonMultimedia',
      title: 'ActivInspire Comparison Multimedia',
    },
    {
      name: 'activInspireComparisonImportFormats',
      title: 'ActivInspire Comparison Import Formats',
    },
    {
      name: 'activInspireComparisonLearnerResponse',
      title: 'ActivInspire Comparison Learner Response',
    },
    {
      name: 'activInspireComparisonAtTheBoard',
      title: 'ActivInspire Comparison at the Board',
    },
    {
      name: 'activInspireComparisonInteractivityAndEngagement',
      title: 'ActivInspire Comparison Interactivity & Engagement',
    },
    {
      name: 'activInspireComparisonRichPowerTool',
      title: 'ActivInspire Comparison Rich Power Tool',
    },
    {
      name: 'accessories',
      title: 'Accessories',
    },
    {
      name: 'webcam',
      title: 'Webcam',
    },
  ],
  icon,
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'main',
    }),
    defineField({
      name: 'localisedTitle',
      title: 'Title',
      type: 'internationalizedArrayString',
      group: 'main',
    }),
    defineField({
      name: 'subTitle',
      title: 'Subtitle',
      type: 'internationalizedArrayString',
      group: 'main',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'main',
      options: {
        source: 'title',
        maxLength: 100,
      },
    }),
    defineField({
      name: 'overview',
      title: 'Overview',
      type: 'blockContent',
    }),
    defineField({
      name: 'releaseDate',
      title: 'Release date',
      type: 'datetime',
    }),
    defineField({
      name: 'featuredImage',
      title: 'Featured Image',
      type: 'image',
      group: 'main',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'finalText',
      title: 'Final normal size line before footer',
      type: 'internationalizedArrayString',
      group: 'main',
    }),
    defineField({
      name: 'prefooterText',
      title: 'Small font line above main footer text',
      type: 'internationalizedArrayString',
      group: 'main',
    }),
    defineField({
      name: 'externalId',
      title: 'External ID',
      type: 'number',
    }),
    defineField({
      name: 'pdfTemplate',
      title: 'PDF Template',
      type: 'number',
      group: 'main',
    }),
    defineField({
      name: 'screenSizeAndResolution',
      title: 'Screen Size and Resolution',
      type: 'internationalizedArrayString',
      group: 'display',
    }),
    defineField({
      name: 'penAndTouchCapability',
      title: 'Pen and Touch Capability',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'multiUserMultiTouchInput',
      title: 'Multi-user and Multi-touch Input',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'crossPlatformCompatibility',
      title: 'Cross-Platform Compatibility',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'intuitiveInterface',
      title: 'Intuitive Interface',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'easyQuickLessonCreation',
      title: 'Easy, Quick Lesson Creation',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'learnerResponseIntegration',
      title: 'Learner Response Integration',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'learnerResponseSystemFeatures',
      title: 'Learner Response System Features',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'resources',
      title: 'Resources',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'languages',
      title: 'Languages',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),

    defineField({
      name: 'deviceType',
      title: 'Device Type',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'operatingSystem',
      title: 'Operating System',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'pcMinSpecs',
      title: 'PC Minimum',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'linuxMinSpecs',
      title: 'Linux Minimum',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),

    defineField({
      name: 'macMinSpecs',
      title: 'MAC Minimum',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'professionalEdition',
      title: 'Professional Edition',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),

    defineField({
      name: 'personalEdition',
      title: 'Personal Edition',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'cpu',
      title: 'CPU',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'gpu',
      title: 'GPU',
      type: 'internationalizedArrayString',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'ram',
      title: 'RAM (GB)',
      type: 'number',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'internalStorage',
      title: 'Internal Storage (GB)',
      type: 'number',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'touchscreenCompatibility',
      title: 'Touchscreen Compatibility',
      type: 'boolean',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'trustedPlatformModule',
      title: 'Trusted Platform Module',
      type: 'boolean',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'trustedPlatformModuleVersion',
      title: 'Trusted Platform Module Version',
      type: 'number',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'cloudBasedUserProfiles',
      title: 'Cloud Based User Profiles',
      type: 'boolean',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'platform',
      title: 'Platform',
      type: 'string',
      group: 'generalSpecifications',
    }),
    defineField({
      name: 'hdmiInDetails',
      title: 'HDMI In',
      type: 'internationalizedArrayString',
      group: 'connectivity',
    }),
    defineField({
      name: 'hdmiOutDetails',
      title: 'HDMI Out',
      type: 'internationalizedArrayString',
      group: 'connectivity',
    }),
    defineField({
      name: 'usbType',
      title: 'USB Type',
      type: 'internationalizedArrayString',
      group: 'connectivity',
    }),
    defineField({
      name: 'usb2',
      title: 'USB 2.0',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'usb3',
      title: 'USB 3.0',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'usbTypeC',
      title: 'USB Type-C',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'combinedAudio35Mm',
      title: 'Combined Audio 3.5 mm',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'networkConnectivity',
      title: 'Network Connectivity',
      type: 'internationalizedArrayString',
      group: 'connectivity',
    }),
    defineField({
      name: 'powerRequirements',
      title: 'Power Requirements',
      type: 'internationalizedArrayString',
      group: 'power',
    }),
    defineField({
      name: 'powerConsumption',
      title: 'Power Consumption',
      type: 'string',
      group: 'power',
    }),
    defineField({
      name: 'powerConsumptionStandby',
      title: 'Power Consumption Standby',
      type: 'string',
      group: 'power',
    }),
    defineField({
      name: 'ultraQuietFanlessDesign',
      title: 'Ultra-Quiet Fanless Design',
      type: 'boolean',
      group: 'power',
    }),
    defineField({
      name: 'operatingTemperatureMin',
      title: 'Operating Temperature Minimum (°C)',
      type: 'number',
      group: 'environmental',
    }),
    defineField({
      name: 'operatingTemperatureMax',
      title: 'Operating Temperature Maximum (°C)',
      type: 'number',
      group: 'environmental',
    }),
    defineField({
      name: 'storageTemperatureMin',
      title: 'Storage Temperature Minimum (°C)',
      type: 'number',
      group: 'environmental',
    }),
    defineField({
      name: 'storageTemperatureMax',
      title: 'Storage Temperature Maximum (°C)',
      type: 'number',
      group: 'environmental',
    }),
    defineField({
      name: 'operatingHumidityMin',
      title: 'Operating Humidity Minimum (%)',
      type: 'number',
      group: 'environmental',
    }),
    defineField({
      name: 'operatingHumidityMax',
      title: 'Operating Humidity Maximum (%)',
      type: 'number',
      group: 'environmental',
    }),
    defineField({
      name: 'storageHumidityMin',
      title: 'Storage Humidity Minimum (%)',
      type: 'number',
      group: 'environmental',
    }),
    defineField({
      name: 'storageHumidityMax',
      title: 'Storage Humidity Maximum (%)',
      type: 'number',
      group: 'environmental',
    }),
    defineField({
      name: 'nonCondensingHumidity',
      title: 'Non-condensing humidity',
      type: 'boolean',
      group: 'environmental',
    }),
    defineField({
      name: 'productDimensionWidth',
      title: 'Product Dimension Width (mm)',
      type: 'string',
      group: 'physicalSpecifications',
    }),
    defineField({
      name: 'productDimensionHeight',
      title: 'Product Dimension Height (mm)',
      type: 'string',
      group: 'physicalSpecifications',
    }),
    defineField({
      name: 'productDimensionDepth',
      title: 'Product Dimension Depth (mm)',
      type: 'string',
      group: 'physicalSpecifications',
    }),
    defineField({
      name: 'packedDimensionWidth',
      title: 'Packed Dimension Width (mm)',
      type: 'string',
      group: 'physicalSpecifications',
    }),
    defineField({
      name: 'packedDimensionHeight',
      title: 'Packed Dimension Height (mm)',
      type: 'string',
      group: 'physicalSpecifications',
    }),
    defineField({
      name: 'packedDimensionDepth',
      title: 'Packed Dimension Depth (mm)',
      type: 'string',
      group: 'physicalSpecifications',
    }),
    defineField({
      name: 'netWeight',
      title: 'Net Weight (kg)',
      type: 'string',
      group: 'physicalSpecifications',
    }),
    defineField({
      name: 'packedWeight',
      title: 'Packed Weight (kg)',
      type: 'string',
      group: 'physicalSpecifications',
    }),
    defineField({
      name: 'wallMountWidth',
      title: 'Wall Mount Width(mm)',
      type: 'number',
      group: 'physicalSpecifications',
    }),
    defineField({
      name: 'wallMountHeight',
      title: 'Wall Mount Height(mm)',
      type: 'number',
      group: 'physicalSpecifications',
    }),
    defineField({
      name: 'wallMountDepth',
      title: 'Wall Mount Depth(mm)',
      type: 'number',
      group: 'physicalSpecifications',
    }),
    defineField({
      name: 'vesaMountPointWidth',
      title: 'VESA Mount Point Width(mm)',
      type: 'string',
      group: 'physicalSpecifications',
    }),
    defineField({
      name: 'vesaMountPointHeight',
      title: 'VESA Mount Point Height(mm)',
      type: 'string',
      group: 'physicalSpecifications',
    }),
    defineField({
      name: 'whatsInTheBox',
      title: "What's in the Box",
      type: 'internationalizedArrayString',
      group: 'packedContents',
    }),
    defineField({
      name: 'regulatoryCertification',
      title: 'Regulatory Certification',
      group: 'complianceCertification',
      type: 'string',
    }),
    defineField({
      name: 'energyStarCertified',
      title: 'energy Star Certified',
      group: 'complianceCertification',
      type: 'boolean',
    }),
    defineField({
      name: 'tradeAgreementsActTaaCompliance',
      title: 'Trade Agreements Act (TAA) Compliance',
      group: 'complianceCertification',
      type: 'internationalizedArrayString',
    }),
    defineField({
      name: 'standardWarranty',
      title: 'Standard WARRANTY',
      type: 'internationalizedArrayString',
      group: 'warranty',
    }),
    defineField({
      name: 'installationBlurb',
      title: 'INSTALLATION Blurb',
      type: 'internationalizedArrayString',
      group: 'installation',
    }),
    defineField({
      name: 'supportBlurb',
      title: 'Support Blurb',
      type: 'internationalizedArrayString',
      group: 'support',
    }),
    defineField({
      name: 'screenType',
      title: 'Screen Type',
      type: 'internationalizedArrayString',
      group: 'display',
    }),
    defineField({
      name: 'diagonalSize',
      title: 'Diagonal Size',
      type: 'internationalizedArrayString',
      group: 'display',
    }),
    defineField({
      name: 'blueLightReduction',
      title: 'Blue Light Reduction',
      type: 'boolean',
      group: 'display',
    }),
    defineField({
      name: 'bondedGlass',
      title: 'Bonded Glass',
      type: 'boolean',
      group: 'display',
    }),
    defineField({
      name: 'aspectRatio',
      title: 'Aspect Ratio',
      type: 'string',
      group: 'display',
    }),
    defineField({
      name: 'dryEraseSurface',
      title: 'Dry Erase Surface',
      type: 'boolean',
      group: 'display',
    }),
    defineField({
      name: 'displayArea',
      title: 'Display Area',
      type: 'internationalizedArrayString',
      group: 'display',
    }),
    defineField({
      name: 'displayColors',
      title: 'Display Colors',
      type: 'internationalizedArrayString',
      group: 'display',
    }),
    defineField({
      name: 'lcdViewingAngle',
      title: 'LCD Viewing Angle (Degrees)',
      type: 'number',
      group: 'display',
    }),
    defineField({
      name: 'lcdResponseTime',
      title: 'LCD Response Time (ms)',
      type: 'number',
      group: 'display',
    }),
    defineField({
      name: 'lcdRefreshRate',
      title: 'LCD Refresh Rate (Hz)',
      type: 'string',
      group: 'display',
    }),
    defineField({
      name: 'lcdBrightness',
      title: 'LCD Brightness (cd/m²)',
      type: 'number',
      group: 'display',
    }),
    defineField({
      name: 'ledLifespan',
      title: 'LED Lifespan (Hours)',
      type: 'number',
      group: 'display',
    }),
    defineField({
      name: 'contrastRatio',
      title: 'Contrast Ratio',
      type: 'internationalizedArrayString',
      group: 'display',
    }),
    defineField({
      name: 'brightness',
      title: 'Brightness (cd/m²)',
      type: 'number',
      group: 'display',
    }),
    defineField({
      name: 'ambientLightSensor',
      title: 'Ambient Light Sensor',
      type: 'boolean',
      group: 'display',
    }),
    defineField({
      name: 'glassHardness',
      title: 'Glass Hardness',
      type: 'internationalizedArrayString',
      group: 'display',
    }),
    defineField({
      name: 'glassType',
      title: 'Glass Type',
      type: 'internationalizedArrayString',
      group: 'display',
    }),
    defineField({
      name: 'glassThickness',
      title: 'Glass Thickness (mm)',
      type: 'number',
      group: 'display',
    }),
    defineField({
      name: 'vellumTouchTechnology',
      title: 'Vellum Touch Technology',
      type: 'boolean',
      group: 'interactivity',
    }),
    defineField({
      name: 'touchTechnology',
      title: 'Touch Technology',
      type: 'array',
      of: [{type: 'string'}],
      options: {
        list: [
          {title: 'None', value: 'none'},
          {title: 'Infrared', value: 'infrared'},
        ],
        layout: 'tags',
      },
      group: 'interactivity',
    }),
    defineField({
      name: 'continuousTouchPoints',
      title: 'Continuous Touch Points',
      type: 'number',
      group: 'interactivity',
    }),
    defineField({
      name: 'touchResolution',
      title: 'Touch Resolution (px)',
      type: 'string',
      group: 'interactivity',
    }),
    defineField({
      name: 'objectSizeResolution',
      title: 'Object Size Resolution',
      type: 'number',
      group: 'interactivity',
    }),
    defineField({
      name: 'touchRefreshRate',
      title: 'Touch Refresh Rate',
      type: 'number',
      group: 'interactivity',
    }),
    defineField({
      name: 'responseTime',
      title: 'Response Time (ms)',
      type: 'number',
      group: 'interactivity',
    }),
    defineField({
      name: 'touchAccuracy',
      title: 'Touch Accuracy (mm)',
      type: 'number',
      group: 'interactivity',
    }),
    defineField({
      name: 'userInput',
      title: 'User Input',
      type: 'internationalizedArrayString',
      group: 'interactivity',
    }),
    defineField({
      name: 'trackingRate',
      title: 'Tracking Rate(m/s)',
      type: 'number',
      group: 'interactivity',
    }),
    defineField({
      name: 'scanRate',
      title: 'Scan Rate (hz)',
      type: 'number',
      group: 'interactivity',
    }),
    defineField({
      name: 'gesturesAndEdgeSwipes',
      title: 'Gestures and Edge Swipes',
      type: 'internationalizedArrayString',
      group: 'interactivity',
    }),
    defineField({
      name: 'uniquePenIds',
      title: 'Unique Pen IDs',
      type: 'number',
      group: 'interactivity',
    }),
    defineField({
      name: 'penAndTouchDifferentiation',
      title: 'Pen and Touch Differentiation',
      type: 'boolean',
      group: 'interactivity',
    }),
    defineField({
      name: 'palmErase',
      title: 'Palm Erase',
      type: 'boolean',
      group: 'interactivity',
    }),
    defineField({
      name: 'palmRejection',
      title: 'Palm Rejection',
      type: 'boolean',
      group: 'interactivity',
    }),
    defineField({
      name: 'pensIncluded',
      title: 'Pens Included',
      //note: render this as e.g. Yes,2
      type: 'number',
      group: 'interactivity',
    }),
    defineField({
      name: 'penType',
      title: 'Pen Type',
      type: 'internationalizedArrayString',
      group: 'interactivity',
    }),
    defineField({
      name: 'penHolder',
      title: 'Pen Holder',
      type: 'internationalizedArrayString',
      group: 'interactivity',
    }),
    defineField({
      name: 'penTipDiameter',
      title: 'Pen Tip Diameter (mm)',
      type: 'number',
      group: 'interactivity',
    }),
    defineField({
      name: 'classroomEssentialApps',
      title: 'Classroom Essential Apps',
      type: 'internationalizedArrayString',
      group: 'interactivity',
    }),
    defineField({
      name: 'compatibility',
      title: 'Compatibility',
      type: 'internationalizedArrayString',
      group: 'interactivity',
    }),
    defineField({
      name: 'dualFrontFacingSpeakers',
      title: 'Dual Front-facing Speakers (W)',
      type: 'string',
      group: 'audio',
    }),
    defineField({
      name: 'isPeak',
      title: 'Peak?',
      type: 'boolean',
      group: 'audio',
    }),
    defineField({
      name: 'opsSlot',
      title: 'OPS Slot',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'hdmiInRear',
      title: 'HDMI In (Rear 2.0)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'hdmiInFront',
      title: 'HDMI In (Front 2.0)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'displayPort',
      title: 'Display Port (1.2)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'usbARear',
      title: 'USB-A (Rear)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'usbA2Rear',
      title: 'USB-A 2.0 (Rear)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'usbA32Rear',
      title: 'USB-A 3.2 Gen 1 (Rear)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'usbA32Front',
      title: 'USB-A 3.2 Gen 1 (Front)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'usbB32Rear',
      title: 'USB-B 3.2 Gen 1 (Touch,Rear)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'usbB32Front',
      title: 'USB-B 3.2 Gen 1 (Touch,Front)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'usbC32Rear',
      title: 'USB-C 3.2 Gen 1 (Rear)',
      type: 'internationalizedArrayString',
      group: 'connectivity',
    }),
    defineField({
      name: 'usbBTouchFront',
      title: 'USB-B Touch (Front)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'usbBTouchRear',
      title: 'USB-B Touch (Rear)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'usbAFront',
      title: 'USB-A (Front)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'microSdSlot',
      title: 'MicroSD Slot',
      type: 'boolean',
      group: 'connectivity',
    }),
    defineField({
      name: 'lanIn',
      title: 'LAN In (RJ45-GBps)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'lanOut',
      title: 'LAN Out (RJ45-GBps)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'wakeOnLan',
      title: 'Wake-on-LAN',
      type: 'boolean',
      group: 'connectivity',
    }),
    defineField({
      name: 'wifi',
      title: 'Wi-Fi (Client)',
      type: 'internationalizedArrayString',
      group: 'connectivity',
    }),
    defineField({
      name: 'bluetooth',
      title: 'Bluetooth',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'hdmiOut',
      title: 'HDMI Out (2.0)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'avIn',
      title: 'AV-In (3.5 mm)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'mic',
      title: 'Mic (3.5 mm)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'audioOut',
      title: 'Audio Out (3.5 mm)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'rs232',
      title: 'RS-232',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'otaUpdates',
      title: 'OTA Updates',
      type: 'boolean',
      group: 'panelManagement',
    }),
    defineField({
      name: 'prometheanAdminTools',
      title: 'Promethean Admin Tools',
      type: 'boolean',
      group: 'panelManagement',
    }),
    defineField({
      name: 'activInspireProfessionalSingleUser',
      title: 'ActivInspire® Professional Single User',
      //note: need to render this as e.g. Included
      type: 'boolean',
      group: 'educationSoftwareLicense',
    }),
    defineField({
      name: 'wirelessProtocol',
      title: 'Wireless Protocol',
      type: 'internationalizedArrayString',
      group: 'connectivity',
    }),
    defineField({
      name: 'dualBand',
      title: 'Dual Band',
      type: 'internationalizedArrayString',
      group: 'connectivity',
    }),
    defineField({
      name: 'mimo',
      title: 'MIMO',
      type: 'string',
      group: 'connectivity',
    }),
    defineField({
      name: 'bandwidth',
      title: 'Bandwidth (Mbps)',
      type: 'number',
      group: 'connectivity',
    }),
    defineField({
      name: 'connector',
      title: 'Connector',
      type: 'string',
      group: 'connectivity',
    }),
    defineField({
      name: 'encryption',
      title: 'Encryption',
      type: 'internationalizedArrayString',
      group: 'connectivity',
    }),
    defineField({
      name: 'combinedTechDimensionsmm',
      title: 'Combined Tech Dimensions mm',
      type: 'string',
      group: 'technicalDrawings',
    }),
    defineField({
      name: 'top',
      title: 'Top',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'back',
      title: 'Back',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'front',
      title: 'Front',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'side',
      title: 'Side',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'back2',
      title: 'Back2',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'front2',
      title: 'Front2',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'side2',
      title: 'Side2',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'back3',
      title: 'Back3',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'front3',
      title: 'Front3',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'side3',
      title: 'Side3',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),

    defineField({
      name: 'back4',
      title: 'Back4',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'front4',
      title: 'Front4',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'side4',
      title: 'Side4',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),

    defineField({
      name: 'back5',
      title: 'Back5',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'front5',
      title: 'Front5',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'side5',
      title: 'Side5',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),

    defineField({
      name: 'back6',
      title: 'Back6',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'front6',
      title: 'Front6',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'side6',
      title: 'Side6',
      type: 'image',
      group: 'technicalDrawings',
      options: {
        hotspot: true,
      },
    }),

    defineField({
      name: 'homepagePersonal',
      title: 'Homepage with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'homepageProfessional',
      title: 'Homepage with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'activitiesPersonal',
      title: 'Activities with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'activitiesProfessional',
      title: 'Activities with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'localResourceSearchPersonal',
      title: 'Local Resource Search with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'localResourceSearchProfessional',
      title: 'Local Resource Search with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'multiPageSelectPersonal',
      title: 'Multi-Page Select with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'multiPageSelectProfessional',
      title: 'Multi-Page Select with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'objectLayeringReorderingPersonal',
      title: 'Object Layering and Reordering with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'objectLayeringReorderingProfessional',
      title: 'Object Layering and Reordering with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'gridMaskPersonal',
      title: 'Grid Mask with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'gridMaskProfessional',
      title: 'Grid Mask with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'textEditingPersonal',
      title: 'Text Editing with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'textEditingProfessional',
      title: 'Text Editing with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'marqueeSelectPersonal',
      title: 'Marquee Select with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'marqueeSelectProfessional',
      title: 'Marquee Select with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'actionsAuthoringProfessional',
      title: 'Actions Authoring with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'actionsAuthoringPersonal',
      title: 'Actions Authoring with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'designModeProfessional',
      title: 'Design Mode with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'designModePersonal',
      title: 'Design Mode with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'themedTemplatesProfessional',
      title: 'Themed Templates with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'themedTemplatesPersonal',
      title: 'Themed Templates with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'objectAlignProfessional',
      title: 'Object Align with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'objectAlignPersonal',
      title: 'Object Align with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'rubberStampProfessional',
      title: 'Rubber Stamp with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'rubberStampPersonal',
      title: 'Rubber Stamp with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'dragACopyProfessional',
      title: 'Drag a Copy with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'dragACopyPersonal',
      title: 'Drag a Copy with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'gridDesignerProfessional',
      title: 'Grid Designer with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'gridDesignerPersonal',
      title: 'Grid Designer with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'uniquelyLabelObjectsProfessional',
      title: 'Uniquely Label Objects with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'uniquelyLabelObjectsPersonal',
      title: 'Uniquely Label Objects with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'pageNotesProfessional',
      title: 'Page Notes with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'pageNotesPersonal',
      title: 'Page Notes with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'shapesLibraryProfessional',
      title: 'Shapes Library with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'shapesLibraryPersonal',
      title: 'Shapes Library with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'croppingToolPersonal',
      title: 'Cropping Tool with Personal',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'croppingToolProfessional',
      title: 'Cropping Tool with Professional',
      type: 'boolean',
      group: 'activInspireComparisonPreperation',
    }),
    defineField({
      name: 'linkDocumentsFlipchartPersonal',
      title: 'Link Documents in Flipchart with Personal',
      type: 'boolean',
      group: 'activInspireComparisonMultimedia',
    }),
    defineField({
      name: 'linkDocumentsFlipchartProfessional',
      title: 'Link Documents in Flipchart with Professional',
      type: 'boolean',
      group: 'activInspireComparisonMultimedia',
    }),
    defineField({
      name: 'graphicsSupportPersonal',
      title: 'Graphics/Image Support with Personal',
      type: 'boolean',
      group: 'activInspireComparisonMultimedia',
    }),
    defineField({
      name: 'graphicsSupportProfessional',
      title: 'Graphics/Image Support with Professional',
      type: 'boolean',
      group: 'activInspireComparisonMultimedia',
    }),
    defineField({
      name: 'screenRecorderPersonal',
      title: 'Screen Recorder with Personal',
      type: 'boolean',
      group: 'activInspireComparisonMultimedia',
    }),
    defineField({
      name: 'screenRecorderProfessional',
      title: 'Screen Recorder with Professional',
      type: 'boolean',
      group: 'activInspireComparisonMultimedia',
    }),
    defineField({
      name: 'soundRecorderPersonal',
      title: 'Sound Recorder with Personal',
      type: 'boolean',
      group: 'activInspireComparisonMultimedia',
    }),
    defineField({
      name: 'soundRecorderProfessional',
      title: 'Sound Recorder with Professional',
      type: 'boolean',
      group: 'activInspireComparisonMultimedia',
    }),
    defineField({
      name: 'asianVerticalTextPersonal',
      title: 'Asian Vertical Text with Personal',
      type: 'boolean',
      group: 'activInspireComparisonMultimedia',
    }),
    defineField({
      name: 'asianVerticalTextProfessional',
      title: 'Asian Vertical Text with Professional',
      type: 'boolean',
      group: 'activInspireComparisonMultimedia',
    }),

    defineField({
      name: 'importSmartNotebookPersonal',
      title: 'Import SMART Notebook™ with Personal',
      type: 'boolean',
      group: 'activInspireComparisonImportFormats',
    }),
    defineField({
      name: 'importSmartNotebookProfessional',
      title: 'Import SMART Notebook™ with Professional',
      type: 'boolean',
      group: 'activInspireComparisonImportFormats',
    }),
    defineField({
      name: 'importSmartGalleryPersonal',
      title: 'Import SMART Gallery™ with Personal',
      type: 'boolean',
      group: 'activInspireComparisonImportFormats',
    }),
    defineField({
      name: 'importSmartGalleryProfessional',
      title: 'Import SMART Gallery™ with Professional',
      type: 'boolean',
      group: 'activInspireComparisonImportFormats',
    }),
    defineField({
      name: 'importPowerPointPersonal',
      title: 'Import PowerPoint® with Personal',
      type: 'boolean',
      group: 'activInspireComparisonImportFormats',
    }),
    defineField({
      name: 'importPowerPointProfessional',
      title: 'Import PowerPoint® with Professional',
      type: 'boolean',
      group: 'activInspireComparisonImportFormats',
    }),
    defineField({
      name: 'importQtiXmlPersonal',
      title: 'Import QTI XML with Personal',
      type: 'boolean',
      group: 'activInspireComparisonImportFormats',
    }),
    defineField({
      name: 'importQtiXmlProfessional',
      title: 'Import QTI XML with Professional',
      type: 'boolean',
      group: 'activInspireComparisonImportFormats',
    }),
    defineField({
      name: 'importPdfPersonal',
      title: 'Import PDF with Personal',
      type: 'boolean',
      group: 'activInspireComparisonImportFormats',
    }),
    defineField({
      name: 'importPdfProfessional',
      title: 'Import PDF with Professional',
      type: 'boolean',
      group: 'activInspireComparisonImportFormats',
    }),
    defineField({
      name: 'exportPdfBmpJpegPersonal',
      title: 'Export PDF, BMP & JPEG with Personal',
      type: 'boolean',
      group: 'activInspireComparisonImportFormats',
    }),
    defineField({
      name: 'exportPdfBmpJpegProfessional',
      title: 'Export PDF, BMP & JPEG with Professional',
      type: 'boolean',
      group: 'activInspireComparisonImportFormats',
    }),
    defineField({
      name: 'integratedActiVotePersonal',
      title: 'Integrated ActiVote and ActivExpression with Personal',
      type: 'boolean',
      group: 'activInspireComparisonLearnerResponse',
    }),
    defineField({
      name: 'integratedActiVoteProfessional',
      title: 'Integrated ActiVote and ActivExpression with Professional',
      type: 'boolean',
      group: 'activInspireComparisonLearnerResponse',
    }),
    defineField({
      name: 'questionManagerPersonal',
      title: 'Question Manager with Personal',
      type: 'boolean',
      group: 'activInspireComparisonLearnerResponse',
    }),
    defineField({
      name: 'questionManagerProfessional',
      title: 'Question Manager with Professional',
      type: 'boolean',
      group: 'activInspireComparisonLearnerResponse',
    }),
    defineField({
      name: 'importExamViewXmlPersonal',
      title: 'Import ExamView® and XML Files with Personal',
      type: 'boolean',
      group: 'activInspireComparisonLearnerResponse',
    }),
    defineField({
      name: 'importExamViewXmlProfessional',
      title: 'Import ExamView® and XML Files with Professional',
      type: 'boolean',
      group: 'activInspireComparisonLearnerResponse',
    }),
    defineField({
      name: 'exportLrsToExcelPersonal',
      title: 'Export LRS Questions and Answers to Excel® with Personal',
      type: 'boolean',
      group: 'activInspireComparisonLearnerResponse',
    }),
    defineField({
      name: 'exportLrsToExcelProfessional',
      title: 'Export LRS Questions and Answers to Excel® with Professional',
      type: 'boolean',
      group: 'activInspireComparisonLearnerResponse',
    }),
    defineField({
      name: 'selfPacedLearningPersonal',
      title: 'Self-Paced Learning with Personal',
      type: 'boolean',
      group: 'activInspireComparisonLearnerResponse',
    }),
    defineField({
      name: 'selfPacedLearningProfessional',
      title: 'Self-Paced Learning with Professional',
      type: 'boolean',
      group: 'activInspireComparisonLearnerResponse',
    }),
    defineField({
      name: 'expressPollPersonal',
      title: 'Express Poll with Personal',
      type: 'boolean',
      group: 'activInspireComparisonLearnerResponse',
    }),
    defineField({
      name: 'expressPollProfessional',
      title: 'Express Poll with Professional',
      type: 'boolean',
      group: 'activInspireComparisonLearnerResponse',
    }),
    defineField({
      name: 'timerPersonal',
      title: 'Timer with Personal',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'timerProfessional',
      title: 'Timer with Professional',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'fillToolPersonal',
      title: 'Fill Tool with Personal',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'fillToolProfessional',
      title: 'Fill Tool with Professional',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'pageScalePersonal',
      title: 'Page Scale with Personal',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'pageScaleProfessional',
      title: 'Page Scale with Professional',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'browsersPersonal',
      title: 'Browsers with Personal',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'browsersProfessional',
      title: 'Browsers with Professional',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'rightClickContextMenuPersonal',
      title: 'Right Click/Context Menu with Personal',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'rightClickContextMenuProfessional',
      title: 'Right Click/Context Menu with Professional',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'penToolPersonal',
      title: 'Pen Tool & Pen Width Indicator with Personal',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'penToolProfessional',
      title: 'Pen Tool & Pen Width Indicator with Professional',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'duplicatePersonal',
      title: 'Duplicate with Personal',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'duplicateProfessional',
      title: 'Duplicate with Professional',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'resetPageToolPersonal',
      title: 'Reset Page Tool with Personal',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'resetPageToolProfessional',
      title: 'Reset Page Tool with Professional',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'pageZoomToolPersonal',
      title: 'Page Zoom Tool with Personal',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'pageZoomToolProfessional',
      title: 'Page Zoom Tool with Professional',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'xyOriginPersonal',
      title: 'XY Origin with Personal',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'xyOriginProfessional',
      title: 'XY Origin with Professional',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'teacherLockPersonal',
      title: 'Teacher Lock with Personal',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'teacherLockProfessional',
      title: 'Teacher Lock with Professional',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'desktopAnnotationPersonal',
      title: 'Desktop Annotation with Personal',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'desktopAnnotationProfessional',
      title: 'Desktop Annotation with Professional',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'dualUserModePersonal',
      title: 'Dual-User Mode with Personal',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'dualUserModeProfessional',
      title: 'Dual-User Mode with Professional',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'penModifiersPersonal',
      title: 'Pen Modifiers with Personal',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'penModifiersProfessional',
      title: 'Pen Modifiers with Professional',
      type: 'boolean',
      group: 'activInspireComparisonAtTheBoard',
    }),
    defineField({
      name: 'assignActionsPersonal',
      title: 'Assign Actions to Objects and Pages with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'assignActionsProfessional',
      title: 'Assign Actions to Objects and Pages with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'magicInkPersonal',
      title: 'Magic Ink & Destructive Eraser with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'magicInkProfessional',
      title: 'Magic Ink & Destructive Eraser with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'applicationSettingsPersonal',
      title: 'Application Settings with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'applicationSettingsProfessional',
      title: 'Application Settings with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'keyboardShortcutsPersonal',
      title: 'Keyboard Shortcuts with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'keyboardShortcutsProfessional',
      title: 'Keyboard Shortcuts with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'dottedDashedLinesPersonal',
      title: 'Dotted and Dashed Lines with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'dottedDashedLinesProfessional',
      title: 'Dotted and Dashed Lines with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'localizedVersionsPersonal',
      title: 'Localized Versions with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'localizedVersionsProfessional',
      title: 'Localized Versions with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'dragActionsObjectsPersonal',
      title: 'Objects with actions can be dragged with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'dragActionsObjectsProfessional',
      title: 'Objects with actions can be dragged with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'customizedProfilesPersonal',
      title: 'Customized Profiles with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'customizedProfilesProfessional',
      title: 'Customized Profiles with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'resizeIconsPersonal',
      title: 'Resize Icons with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'resizeIconsProfessional',
      title: 'Resize Icons with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'userDefinedButtonsPersonal',
      title: 'User Defined Buttons with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'userDefinedButtonsProfessional',
      title: 'User Defined Buttons with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'dragOnButtonsPersonal',
      title: 'Drag-on Buttons with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'dragOnButtonsProfessional',
      title: 'Drag-on Buttons with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'handwritingRecognitionToolPersonal',
      title: 'Handwriting Recognition Tool with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'handwritingRecognitionToolProfessional',
      title: 'Handwriting Recognition Tool with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'convertToTextToolPersonal',
      title: 'Convert to Text Tool with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'convertToTextToolProfessional',
      title: 'Convert to Text Tool with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'shapeRecognitionToolPersonal',
      title: 'Shape Recognition Tool with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'shapeRecognitionToolProfessional',
      title: 'Shape Recognition Tool with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'convertToShapeToolPersonal',
      title: 'Convert to Shape Tool with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'convertToShapeToolProfessional',
      title: 'Convert to Shape Tool with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'pageTurnEffectsPersonal',
      title: 'Page Turn Effects with Personal',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'pageTurnEffectsProfessional',
      title: 'Page Turn Effects with Professional',
      type: 'boolean',
      group: 'activInspireComparisonInteractivityAndEngagement',
    }),
    defineField({
      name: 'clockPersonal',
      title: 'Clock with Personal',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'clockProfessional',
      title: 'Clock with Professional',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'snapObjectToGridPersonal',
      title: 'Snap Object to Grid with Personal',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'snapObjectToGridProfessional',
      title: 'Snap Object to Grid with Professional',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'spotlightPersonal',
      title: 'Spotlight with Personal',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'spotlightProfessional',
      title: 'Spotlight with Professional',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'timeStampingPersonal',
      title: 'Time Stamping with Personal',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'timeStampingProfessional',
      title: 'Time Stamping with Professional',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'colorPickerPersonal',
      title: 'Color Picker with Personal',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'colorPickerProfessional',
      title: 'Color Picker with Professional',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'tickertapePersonal',
      title: 'Tickertape with Personal',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'tickertapeProfessional',
      title: 'Tickertape with Professional',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'compassToolPersonal',
      title: 'Compass Tool with Personal',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'compassToolProfessional',
      title: 'Compass Tool with Professional',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'revealerToolPersonal',
      title: 'Revealer Tool with Personal',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'revealerToolProfessional',
      title: 'Revealer Tool with Professional',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'calculatorPersonal',
      title: 'Calculator with Personal',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'calculatorProfessional',
      title: 'Calculator with Professional',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'onScreenKeyboardPersonal',
      title: 'On-screen Keyboard with Personal',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'onScreenKeyboardProfessional',
      title: 'On-screen Keyboard with Professional',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'diceToolPersonal',
      title: 'Dice Tool with Personal',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'diceToolProfessional',
      title: 'Dice Tool with Professional',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'spellcheckFlipchartPersonal',
      title: 'Spellcheck reviews entire flipchart with Personal',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'spellcheckFlipchartProfessional',
      title: 'Spellcheck reviews entire flipchart with Professional',
      type: 'boolean',
      group: 'activInspireComparisonRichPowerTool',
    }),
    defineField({
      name: 'standsProjectors',
      title: 'Stands & Projectors',
      type: 'boolean',
      group: 'accessories',
    }),
    defineField({
      name: 'activSoundBar',
      title: 'ActivSoundBar',
      type: 'boolean',
      group: 'accessories',
    }),
    defineField({
      name: 'sensor',
      title: 'Sensor',
      type: 'boolean',
      group: 'webcam',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      date: 'releaseDate',
      media: 'featuredImage',
    },
    prepare(selection) {
      const year = selection.date && selection.date.split('-')[0]

      return {
        title: `${selection.title} ${year ? `(${year})` : ''}`,
        date: selection.date,
        media: selection.media,
      }
    },
  },
})
